const LANG = {
  // Tab names
  recipes: { en: "Recipes", es: "Recetas" },
  mealPlan: { en: "Meal Plan", es: "Plan Semanal" },
  groceryList: { en: "Grocery List", es: "Lista de Compras" },

  // Common
  search: { en: "Search recipes...", es: "Buscar recetas..." },
  all: { en: "All", es: "Todas" },
  breakfast: { en: "Breakfast", es: "Desayuno" },
  lunch: { en: "Lunch", es: "Almuerzo" },
  dinner: { en: "Dinner", es: "Cena" },
  snack: { en: "Snack", es: "Snack" },
  servings: { en: "Servings", es: "Porciones" },
  prepTime: { en: "Prep", es: "Prep" },
  cookTime: { en: "Cook", es: "Cocción" },
  minutes: { en: "min", es: "min" },
  ingredients: { en: "Ingredients", es: "Ingredientes" },
  instructions: { en: "Instructions", es: "Instrucciones" },
  addRecipe: { en: "Add Recipe", es: "Agregar Receta" },
  editRecipe: { en: "Edit Recipe", es: "Editar Receta" },
  deleteRecipe: { en: "Delete Recipe", es: "Eliminar Receta" },
  resetToOriginal: { en: "Reset to Original", es: "Restaurar Original" },
  save: { en: "Save", es: "Guardar" },
  cancel: { en: "Cancel", es: "Cancelar" },
  delete: { en: "Delete", es: "Eliminar" },
  confirm: { en: "Confirm", es: "Confirmar" },

  // Meal Plan
  clearWeek: { en: "Clear Week", es: "Limpiar Semana" },
  addMeal: { en: "Add Meal", es: "Agregar Comida" },
  selectSlot: { en: "Select meal type", es: "Seleccionar tipo de comida" },
  selectRecipe: { en: "Select a recipe", es: "Seleccionar una receta" },
  customSlot: { en: "Custom", es: "Personalizado" },
  customSlotName: { en: "Slot name", es: "Nombre del slot" },
  removeMeal: { en: "Remove", es: "Quitar" },
  confirmClearWeek: { en: "Clear all meals for this week?", es: "¿Limpiar todas las comidas de esta semana?" },

  // Grocery List
  generateFromPlan: { en: "Generate from Meal Plan", es: "Generar del Plan Semanal" },
  addItem: { en: "Add item...", es: "Agregar artículo..." },
  clearChecked: { en: "Clear Checked", es: "Limpiar Marcados" },
  autoGenerated: { en: "From Meal Plan", es: "Del Plan Semanal" },
  manualItems: { en: "Manual Items", es: "Artículos Manuales" },
  noItemsYet: { en: "No items yet. Generate from your meal plan or add manually.", es: "Sin artículos. Genera desde tu plan semanal o agrega manualmente." },

  // Settings / Export / Import
  settings: { en: "Settings", es: "Configuración" },
  exportData: { en: "Export Data", es: "Exportar Datos" },
  importData: { en: "Import Data", es: "Importar Datos" },
  mergeOrReplace: { en: "Merge with existing data or replace?", es: "¿Combinar con datos existentes o reemplazar?" },
  merge: { en: "Merge", es: "Combinar" },
  replace: { en: "Replace", es: "Reemplazar" },
  exportSuccess: { en: "Data exported!", es: "¡Datos exportados!" },
  importSuccess: { en: "Data imported!", es: "¡Datos importados!" },

  // Days
  mon: { en: "Mon", es: "Lun" },
  tue: { en: "Tue", es: "Mar" },
  wed: { en: "Wed", es: "Mié" },
  thu: { en: "Thu", es: "Jue" },
  fri: { en: "Fri", es: "Vie" },
  sat: { en: "Sat", es: "Sáb" },
  sun: { en: "Sun", es: "Dom" },

  // Recipe form
  recipeName: { en: "Recipe name", es: "Nombre de la receta" },
  category: { en: "Category", es: "Categoría" },
  prepTimeMin: { en: "Prep time (min)", es: "Tiempo de preparación (min)" },
  cookTimeMin: { en: "Cook time (min)", es: "Tiempo de cocción (min)" },
  servingsCount: { en: "Servings", es: "Porciones" },
  ingredientName: { en: "Ingredient", es: "Ingrediente" },
  amount: { en: "Amount", es: "Cantidad" },
  unit: { en: "Unit", es: "Unidad" },
  addIngredient: { en: "Add Ingredient", es: "Agregar Ingrediente" },
  addStep: { en: "Add Step", es: "Agregar Paso" },
  step: { en: "Step", es: "Paso" },
  removeIngredient: { en: "Remove", es: "Quitar" },
  removeStep: { en: "Remove", es: "Quitar" },

  // Confirmations
  confirmDelete: { en: "Delete this recipe?", es: "¿Eliminar esta receta?" },
  confirmImportReplace: { en: "This will replace all your current data. Continue?", es: "Esto reemplazará todos tus datos actuales. ¿Continuar?" },
};
